version: "3.3"
services:

 eurekaserver:
   build: ./eureka-server
   restart: on-failure
   ports:
     - "6761:6761"
     - "6762:6762"
   networks:
     - dev

 redisserver:
   image: sameersbn/redis:latest
   ports:
     - "6379:6379"
   volumes:
     - redis_data:/var/lib/redis
   restart: always
   networks:
     - dev

 mysql:
     image: mysql:latest
     restart: always
     command: --default-authentication-plugin=mysql_native_password
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: abc123
       MYSQL_USER: 'test'
       MYSQL_PASS: 'test'
     volumes:
       - mysql_data:/var/lib/mysql
     networks:
        - dev



 gateway:
   build: ./gateway
   ports:
     - "8088:8088"
   environment:
     - SPRING_PROFILES_ACTIVE=svt
   depends_on: #先启动eurekaserver
     - eurekaserver
   links: #从这个容器访问eurekaserver容器
      - eurekaserver
   networks:
      - dev
 account:
    build: ./account
    ports:
      - "8083:8083"
    environment:
         - SPRING_PROFILES_ACTIVE=svt
    depends_on:
      - eurekaserver
    links:
      - eurekaserver
    networks:
      - dev

 xfauth:
     build: ./xfauth
     ports:
       - "5000:5000"
     environment:
          - SPRING_PROFILES_ACTIVE=svt
     depends_on:
       - eurekaserver
       - redisserver
       - mysql
     links:
       - eurekaserver
       - mysql
       - redisserver
     networks:
        - dev

networks:
  dev:
    driver: bridge

volumes:
  redis_data:
  mysql_data:

